name = "Ingenuous"
uuid = "f41de3ae-e36c-4881-be7e-ef5b06c31f70"
authors = ["Richard Tjörnhammar <richard.tjornhammar@gmail.com>"]
version = "0.2.5"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
